log:
  level: debug
  disable_sentry: true

db:
  url: "postgres://utluser:utlpass@utl_db:5432/usdc_transfer_listener?sslmode=disable"

listener:
  addr: :8080

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: usdc-transfer-listener-svc
  service_port: 80

keys:
  infura_api: "${INFURA_API_KEY}"